# **Exercise: Pandas Merging**

Gunakan datasets:
- audi.csv
- hyundai.csv
- toyota.csv

Dataset ini berisi data penjualan mobil bekas

Load ketiga dataset di atas, kemudian simpan masing-masing dataset ke dalam sebuah variable!

Selain menggunakan materi yang telah didapatkan, gunakan juga skill googling Anda untuk mempermudah mengerjakan latihan ini.

In [12]:
import numpy as np
import pandas as pd

In [7]:
df = pd.DataFrame({"A":[1,1,2,2], "B":[10,20,30,40]})
print(df.groupby("A")["B"].sum())

A
1    30
2    70
Name: B, dtype: int64

Dataset: https://www.kaggle.com/adityadesai13/used-car-dataset-ford-and-mercedes?select=toyota.csv

Di bawah ini adalah tampilan 5 baris pertama dari ketiga dataset tersebut

**Audi**

In [8]:
df_audi = pd.read_csv('audi.csv')
df_audi.head()

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

**Hyundai**

In [9]:
df_hyundai = pd.read_csv('hyundai.csv')
df_hyundai.head()

,model,year,price,transmission,mileage,fuelType,tax(£),mpg,engineSize
0,I20,2017,7999,Manual,17307,Petrol,145,58.9,1.2
1,Tucson,2016,14499,Automatic,25233,Diesel,235,43.5,2.0
2,Tucson,2016,11399,Manual,37877,Diesel,30,61.7,1.7
3,I10,2016,6499,Manual,23789,Petrol,20,60.1,1.0
4,IX35,2015,10199,Manual,33177,Diesel,160,51.4,2.0

**Toyota**

In [13]:
df_toyota = pd.read_csv('toyota.csv')
df_toyota.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

## **No.1**

- Jika Anda perhatikan, nama kolom 'tax(£)' di dataset hyundai berbeda dengan di dataset lainnya.
- Ubah nama kolom tersebut menjadi 'tax' agar sama dengan di dataset yang lain.

In [10]:
df_hyundai.rename(columns={"tax(£)": "tax"}, inplace=True)
df_hyundai

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,I20,2017,7999,Manual,17307,Petrol,145,58.9,1.2
1,Tucson,2016,14499,Automatic,25233,Diesel,235,43.5,2.0
2,Tucson,2016,11399,Manual,37877,Diesel,30,61.7,1.7
3,I10,2016,6499,Manual,23789,Petrol,20,60.1,1.0
4,IX35,2015,10199,Manual,33177,Diesel,160,51.4,2.0
...,...,...,...,...,...,...,...,...,...
4855,I30,2016,8680,Manual,25906,Diesel,0,78.4,1.6
4856,I40,2015,7830,Manual,59508,Diesel,30,65.7,1.7
4857,I10,2017,6830,Manual,13810,Petrol,20,60.1,1.0
4858,Tucson,2018,13994,Manual,23313,Petrol,145,44.8,1.6
4859,Tucson,2016,15999,Automatic,11472,Diesel,125,57.6,1.7

## **No.2**

- Buat kolom baru bernama 'brand' dengan isi nama brand mobilnya, letakkan pada kolom paling kiri.
- Misalnya:
    - Untuk data frame audi, isi kolom 'brand' dengan 'Audi' semua!
    - Untuk data frame hyundai, isi kolom 'brand' dengan 'Hyundai' semua!
    - Untuk data frame toyota, isi kolom 'brand' dengan 'Toyota'semua!

In [14]:
df_audi["brand"] = pd.Series(["Audi" for x in range(len(df_audi.index))])
df_hyundai["brand"] = pd.Series(["Hyundai" for x in range(len(df_audi.index))])
df_toyota["brand"] = pd.Series(["Toyota" for x in range(len(df_audi.index))])
display(df_audi)
display(df_hyundai)
display(df_toyota)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,A1,2017,12500,Manual,15735,Petrol,150,55.4,1.4,Audi
1,A6,2016,16500,Automatic,36203,Diesel,20,64.2,2.0,Audi
2,A1,2016,11000,Manual,29946,Petrol,30,55.4,1.4,Audi
3,A4,2017,16800,Automatic,25952,Diesel,145,67.3,2.0,Audi
4,A3,2019,17300,Manual,1998,Petrol,145,49.6,1.0,Audi
...,...,...,...,...,...,...,...,...,...,...
10663,A3,2020,16999,Manual,4018,Petrol,145,49.6,1.0,Audi
10664,A3,2020,16999,Manual,1978,Petrol,150,49.6,1.0,Audi
10665,A3,2020,17199,Manual,609,Petrol,150,49.6,1.0,Audi
10666,Q3,2017,19499,Automatic,8646,Petrol,150,47.9,1.4,Audi
10667,Q3,2016,15999,Manual,11855,Petrol,150,47.9,1.4,Audi

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,I20,2017,7999,Manual,17307,Petrol,145,58.9,1.2,Hyundai
1,Tucson,2016,14499,Automatic,25233,Diesel,235,43.5,2.0,Hyundai
2,Tucson,2016,11399,Manual,37877,Diesel,30,61.7,1.7,Hyundai
3,I10,2016,6499,Manual,23789,Petrol,20,60.1,1.0,Hyundai
4,IX35,2015,10199,Manual,33177,Diesel,160,51.4,2.0,Hyundai
...,...,...,...,...,...,...,...,...,...,...
4855,I30,2016,8680,Manual,25906,Diesel,0,78.4,1.6,Hyundai
4856,I40,2015,7830,Manual,59508,Diesel,30,65.7,1.7,Hyundai
4857,I10,2017,6830,Manual,13810,Petrol,20,60.1,1.0,Hyundai
4858,Tucson,2018,13994,Manual,23313,Petrol,145,44.8,1.6,Hyundai
4859,Tucson,2016,15999,Automatic,11472,Diesel,125,57.6,1.7,Hyundai

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,GT86,2016,16000,Manual,24089,Petrol,265,36.2,2.0,Toyota
1,GT86,2017,15995,Manual,18615,Petrol,145,36.2,2.0,Toyota
2,GT86,2015,13998,Manual,27469,Petrol,265,36.2,2.0,Toyota
3,GT86,2017,18998,Manual,14736,Petrol,150,36.2,2.0,Toyota
4,GT86,2017,17498,Manual,36284,Petrol,145,36.2,2.0,Toyota
...,...,...,...,...,...,...,...,...,...,...
6733,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0,Toyota
6734,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3,Toyota
6735,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4,Toyota
6736,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3,Toyota
6737,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3,Toyota

## **No.3**

- Gabungkan ketiga data frame tersebut menjadi sebuah data frame bernama df_car. Atur agar indexnya tidak ada yang berulang.

In [15]:
#df_car = df_audi.merge(df_hyundai, on='brand', how='inner').merge(df_toyota, on='brand', how='outer').dropna(axis=1)
df_car = pd.concat([df_audi, df_hyundai, df_toyota], axis=0, ignore_index=True)
df_car

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,A1,2017,12500,Manual,15735,Petrol,150,55.4,1.4,Audi
1,A6,2016,16500,Automatic,36203,Diesel,20,64.2,2.0,Audi
2,A1,2016,11000,Manual,29946,Petrol,30,55.4,1.4,Audi
3,A4,2017,16800,Automatic,25952,Diesel,145,67.3,2.0,Audi
4,A3,2019,17300,Manual,1998,Petrol,145,49.6,1.0,Audi
...,...,...,...,...,...,...,...,...,...,...
22261,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0,Toyota
22262,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3,Toyota
22263,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4,Toyota
22264,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3,Toyota
22265,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3,Toyota

## **No.4**

- Pada kolom 'model' di sebagian data, ada whitespace tambahan di awal atau di akhir yang tidak berguna.
- Hapus whitespace tersebut dari semua data pada kolom 'model'!

In [16]:
df_car["model"].str.strip()
df_car

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand
0,A1,2017,12500,Manual,15735,Petrol,150,55.4,1.4,Audi
1,A6,2016,16500,Automatic,36203,Diesel,20,64.2,2.0,Audi
2,A1,2016,11000,Manual,29946,Petrol,30,55.4,1.4,Audi
3,A4,2017,16800,Automatic,25952,Diesel,145,67.3,2.0,Audi
4,A3,2019,17300,Manual,1998,Petrol,145,49.6,1.0,Audi
...,...,...,...,...,...,...,...,...,...,...
22261,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0,Toyota
22262,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3,Toyota
22263,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4,Toyota
22264,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3,Toyota
22265,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3,Toyota

## **No.5**

- Dari df_car, tampilkan rata-rata pajak/tax berdasarkan brand dan transmission. Lalu urutkan dari tax yang paling tinggi.

In [17]:
mediantax = df_car.groupby(["brand", "transmission"])["tax"].median().sort_values(ascending=False)
print(mediantax)

brand    transmission
Audi     Automatic       145.0
         Manual          145.0
         Semi-Auto       145.0
Hyundai  Automatic       145.0
         Manual          145.0
         Semi-Auto       145.0
Toyota   Manual          145.0
         Semi-Auto       145.0
         Automatic       135.0
Hyundai  Other            72.5
Toyota   Other             0.0
Name: tax, dtype: float64

## **No.6**

- Anda diminta untuk mencari mobil Toyota Camry yang harganya (price) di bawah rata-rata harga Camry dan jarak tempuhnya (mileage) di bawah rata-rata mileage Camry juga.
- Tampilkan mobil yang sesuai dengan kriteria tersebut!

In [18]:
camry = df_car[(df_car["brand"] == "Toyota") & (df_car["model"] == "Camry")]
avgprice = camry["price"].mean()
avgmiles = camry["mileage"].mean()
bestcamry = camry[(camry["price"] < avgprice) & (camry["mileage"] < avgmiles)]
print(bestcamry)

Empty DataFrame
Columns: [model, year, price, transmission, mileage, fuelType, tax, mpg, engineSize, brand]
Index: []

## **No.7**

Simpan df_car ke dalam format .csv dengan nama file 'all_cars.csv'!

In [19]:
df_car.to_csv('all_cars.cxv', index=False)

## **No.8**

Tampilkan mobil paling mahal!

In [20]:
expensive = df_car.groupby(["brand", "model"])["price"].max().sort_values(ascending=False)
print(expensive)

#df_car.loc[df_car["price"].idmax()]

brand    model
Audi     R8               145000
         RS6              109495
Hyundai  I10               92000
Audi     Q7                89990
         Q8                89750
         A8                78990
         RS4               71990
         Q5                67990
         RS5               66990
         A6                60000
Toyota   Supra             59995
Audi     A5                59995
         SQ7               59950
         SQ5               56450
         TT                54995
Toyota   Land Cruiser      54991
Audi     A7                53750
         A4                52000
Toyota   PROACE VERSO      47990
Audi     RS3               47990
         S4                45888
         S8                44991
Hyundai  Santa Fe          43995
Audi     Q3                43990
         Q2                40000
Toyota   Hilux             39257
         RAV4              37440
Audi     A3                36990
         RS7               33490
Toyota   Prius             31995
         GT86              31000
         C-HR              30990
Audi     A1                30950
Toyota   Camry             29990
         Corolla           29450
Hyundai  Ioniq             28995
         Tucson            28500
Audi     S3                27995
Hyundai  I30               27995
Toyota   Yaris             25995
Hyundai  Kona              25280
         I800              24995
         I40               21990
Toyota   Auris             19300
Audi     S5                18950
Toyota   Verso             17995
Hyundai  I20               16998
Toyota   Avensis           16495
Hyundai  IX20              15495
Toyota   Aygo              15000
Hyundai  IX35              12500
         Veloster           8300
Toyota   Verso-S            6995
         IQ                 5995
         Urban Cruiser      4995
Hyundai  Terracan           3290
Audi     A2                 2490
Hyundai  Getz               2395
         Amica              1750
         Accent             1295
Name: price, dtype: int64

## **No.9**

Pada tahun berpa mobil Toyota paling banyak muncul

In [21]:
dftoyota = df_car[df_car["brand"] == "Toyota"]
toyotafreq = dftoyota["year"].mode()[0]

print(toyotafreq)

2017

## **No.10**

Tampilkan jumlah mobil totoya keluaran 2019 untuk tiap model

In [22]:
toyota2019 = df_car[(df_car["brand"] == "Toyota") & (df_car["year"] == 2019)]
result = toyota2019.groupby("model")["brand"].count()
print(result)

model
Auris             3
Aygo            379
C-HR            108
Camry            10
Corolla         227
GT86             19
Hilux            19
Land Cruiser     15
PROACE VERSO     13
Prius            37
RAV4             46
Supra            12
Yaris           398
Name: brand, dtype: int64

## **No.11**

Tampilkan model dari Toyota yang paling irit (mpg paling tinggi)

In [23]:
dftoyota = df_car[df_car["brand"] == "Toyota"]
mpgtoyota = dftoyota.loc[dftoyota["mpg"].idxmax(), "model"]
print(mpgtoyota)

 Prius

## **No.12**

Tamplikan mobil yang nama modelnya mengandung huruf 'x'!

In [25]:
df_x = df_car[df_car["model"].str.contains("x")]
print(df_x)

        model  year  price transmission  mileage fuelType  tax   mpg  \
22076   Hilux  2018  20998       Manual    13099   Diesel  260  40.4
22077   Hilux  2016  13695       Manual    69921   Diesel  260  40.4
22078   Hilux  2017  18250       Manual    32000   Diesel  260  40.4
22079   Hilux  2014  11495       Manual    88912   Diesel  260  38.7
22080   Hilux  2019  28495    Automatic     3350   Diesel  260   2.8
...       ...   ...    ...          ...      ...      ...  ...   ...
22157   Hilux  2013  12000    Automatic    92007   Diesel  260  32.8
22158   Hilux  2014   9694       Manual    93334   Diesel  260  38.7
22159   Hilux  2019  24995    Automatic    17200   Diesel  260  36.2
22160   Hilux  2016  15650       Manual    20250   Diesel  265  40.4
22161   Hilux  2015   9995       Manual    80069   Diesel  260  38.7

       engineSize   brand
22076         2.4  Toyota
22077         2.4  Toyota
22078         2.4  Toyota
22079         2.5  Toyota
22080         2.4  Toyota
...           ...     ...
22157         3.0  Toyota
22158         2.5  Toyota
22159         2.4  Toyota
22160         2.4  Toyota
22161         2.5  Toyota

[86 rows x 10 columns]

## **No.13**

Buat dataframe baru dengan pivot table berisi rata-rata tax tiap transmission dan fuelType

In [26]:
pivot_tax = df_car.pivot_table(values="tax", index="transmission", columns="fuelType", aggfunc="mean")
print(pivot_tax)

fuelType          Diesel      Hybrid       Other      Petrol
transmission
Automatic     153.904594   67.880993  104.405941  148.363243
Manual         88.275379  138.400000   30.000000  110.354446
Other                NaN    0.000000         NaN  145.000000
Semi-Auto     143.757590  122.192982         NaN  142.955056

## **No.14**

Ada berapa model yang hanya ada 1 unit mobil di dataset ini? (mobil langka)

In [37]:
model_amt = df_car.groupby("model")["brand"].count()
rare_models = model_amt[model_amt == 1]
print("There are:",len(rare_models), "rare car models")

There are: 4 rare car models