<br>

---

<br>

# Pandas Data Manipulation #1

Total Question: 11 Task
Objective: Perform various data manipulation tasks to understand factors influencing employee attrition, including salary, department, job satisfaction, and years at the company.

## Step 1.

Import the required libraries

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": [10, 20, 30, 40]
}, index = ["w","x","y","z"])
print(df.iloc[1:3,0])

x    2
y    3
Name: A, dtype: int64

<br>

## Step 2. Load and Explore Dataset

Load dataset into pandas

In [6]:
df = pd.read_csv("Employee-Attrition.csv")
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

<br>

## Step 3. Basic Exploration and Understanding

1. Check the structure and summary of the dataset.
1. Check for missing values.

In [7]:
# 1. Check the structure and summary of the dataset
# 1.1 Find the number of rows, columns, and data types of each column.
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

(1470, 35)

In [8]:
# 1. Check the structure and summary of the dataset
# 1.2  Get basic statistics about the numeric columns (e.g., age, monthly income, etc.)
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
# 2. Check for missing values.
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

<br>

## Step 4. Remove unnecessary columns
Some columns, like **EmployeeCount**, **Over18**, and **EmployeeNumber**, might not add much value to the analysis. Remove them.

In [11]:
df.drop(columns= ["EmployeeCount", "Over18", "EmployeeNumber"])
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

<br>

## Step 5. Create new columns

Create a column seniority_level based on YearsAtCompany:
- junior for employees with less than 3 years
- mid-level for employees with 3 to 6 years
- senior for employees with more than 6 years

In [18]:
def seniority(years):
    if years < 3:
        return "junior"
    elif years <= 6:
        return "mid-level"
    else:
        return "senior"

df["seniority_level"] = df["YearsAtCompany"].apply(seniority)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,seniority_level
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,80,0,8,0,1,6,4,0,5,mid-level
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,80,1,10,3,3,10,7,1,7,senior
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,80,0,7,3,3,0,0,0,0,junior
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,80,0,8,3,3,8,7,3,0,senior
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,80,1,6,3,3,2,2,2,2,junior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,80,1,17,3,3,5,2,0,3,mid-level
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,80,1,9,5,3,7,7,1,7,senior
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,80,1,6,0,3,6,2,0,3,mid-level
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,80,0,17,3,2,9,6,0,8,senior
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,80,0,6,3,4,4,3,1,2,mid-level

<br>

## Step 6. Group by department and calculate average salary
Group the data by Department and calculate the average MonthlyIncome for each department

In [16]:
df.groupby("Department")["MonthlyIncome"].mean()

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

<br>

## Step 7. Analyze attrition rates
1. Calculate the overall attrition rate (percentage of employees who have left).
1. Calculate the attrition rate by seniority_level and JobRole.

In [ ]:
# Overall attrition rate
attrition_rate = (df["Attrition"] == "Yes").sum() / len(df) * 100
print(f"Overall attrition rate: {attrition_rate:.2f}%")

Overall attrition rate: {attrition_rate:.2}%

In [24]:
# Attrition rate by seniority level
df.groupby("seniority_level")["Attrition"].apply(lambda x: (x == "Yes").mean() * 100)

seniority_level
junior       29.824561
mid-level    13.529412
senior       10.679612
Name: Attrition, dtype: float64

In [25]:
# Attrition rate by job role
df.groupby("JobRole")["Attrition"].apply(lambda x: (x == "Yes").mean() * 100)

JobRole
Healthcare Representative     6.870229
Human Resources              23.076923
Laboratory Technician        23.938224
Manager                       4.901961
Manufacturing Director        6.896552
Research Director             2.500000
Research Scientist           16.095890
Sales Executive              17.484663
Sales Representative         39.759036
Name: Attrition, dtype: float64

<br>

## Step 8. Filter the dataset

1. Filter the dataset to show only employees in the Sales department with more than 5 years at the company who have left (attrition = Yes)
1. Find all employees with a JobSatisfaction rating of 4 (highest) who still left the company.

In [30]:
# Sales department employees with more than 5 years who left
df[(df["Department"] == "Sales") & (df["YearsAtCompany"] > 5) & (df["Attrition"] == "Yes")]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,seniority_level
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,80,0,8,0,1,6,4,0,5,mid-level
89,46,Yes,Travel_Rarely,669,Sales,9,2,Medical,1,118,...,80,0,9,3,3,9,8,4,7,senior
107,25,Yes,Travel_Rarely,240,Sales,5,3,Marketing,1,142,...,80,0,6,1,3,6,4,0,3,mid-level
124,31,Yes,Travel_Rarely,249,Sales,6,4,Life Sciences,1,163,...,80,0,12,3,2,7,7,7,7,senior
205,29,Yes,Travel_Rarely,121,Sales,27,3,Marketing,1,283,...,80,3,10,3,2,10,4,1,9,senior
210,32,Yes,Travel_Rarely,1045,Sales,4,4,Medical,1,291,...,80,0,14,2,2,14,8,9,8,senior
216,30,Yes,Travel_Frequently,334,Sales,26,4,Marketing,1,299,...,80,0,9,5,2,6,3,0,1,mid-level
293,26,Yes,Travel_Rarely,950,Sales,4,4,Marketing,1,401,...,80,0,8,0,3,8,7,7,4,senior
366,41,Yes,Travel_Frequently,143,Sales,4,3,Marketing,1,488,...,80,0,8,5,3,8,7,7,7,senior
368,40,Yes,Travel_Rarely,575,Sales,22,2,Marketing,1,492,...,80,2,8,6,3,6,4,1,0,mid-level
607,49,Yes,Travel_Rarely,1184,Sales,11,3,Marketing,1,840,...,80,2,9,3,4,9,8,7,7,senior
608,55,Yes,Travel_Rarely,436,Sales,2,1,Medical,1,842,...,80,0,12,3,2,9,7,7,3,senior
693,36,Yes,Travel_Rarely,530,Sales,3,1,Life Sciences,1,967,...,80,1,16,6,3,16,7,3,7,senior
695,37,Yes,Travel_Rarely,625,Sales,1,4,Life Sciences,1,970,...,80,0,17,2,1,14,1,11,7,senior
749,52,Yes,Travel_Rarely,266,Sales,2,1,Marketing,1,1038,...,80,1,33,3,3,32,14,6,9,senior
791,35,Yes,Travel_Rarely,1204,Sales,4,3,Technical Degree,1,1100,...,80,0,9,2,3,8,7,4,7,senior
836,29,Yes,Travel_Rarely,408,Sales,23,1,Life Sciences,1,1165,...,80,1,11,3,1,11,8,3,10,senior
838,42,Yes,Travel_Frequently,481,Sales,12,3,Life Sciences,1,1167,...,80,0,22,2,2,21,9,13,14,senior
913,45,Yes,Travel_Rarely,1449,Sales,2,3,Marketing,1,1277,...,80,0,26,2,3,24,10,1,11,senior
947,52,Yes,Travel_Rarely,1030,Sales,5,3,Life Sciences,1,1319,...,80,0,10,2,2,8,7,7,7,senior
975,55,Yes,Travel_Rarely,267,Sales,13,4,Marketing,1,1372,...,80,0,24,2,2,19,7,3,8,senior
1031,46,Yes,Travel_Rarely,377,Sales,9,3,Marketing,1,1457,...,80,1,28,1,4,7,7,4,3,senior
1058,34,Yes,Travel_Rarely,790,Sales,24,4,Medical,1,1489,...,80,0,16,2,4,15,9,10,10,senior
1106,30,Yes,Travel_Rarely,740,Sales,1,3,Life Sciences,1,1562,...,80,1,10,4,3,10,8,6,7,senior
1162,35,Yes,Travel_Rarely,737,Sales,10,3,Medical,1,1639,...,80,0,15,3,3,13,12,6,0,senior
1186,35,Yes,Travel_Frequently,880,Sales,12,4,Other,1,1667,...,80,0,13,2,4,11,9,6,7,senior
1204,48,Yes,Travel_Frequently,708,Sales,7,2,Medical,1,1691,...,80,2,19,3,3,9,7,7,7,senior
1223,47,Yes,Travel_Frequently,1093,Sales,9,3,Life Sciences,1,1716,...,80,0,25,3,1,23,5,14,10,senior
1281,35,Yes,Travel_Rarely,303,Sales,27,3,Life Sciences,1,1797,...,80,0,10,2,3,10,7,7,7,senior
1333,46,Yes,Travel_Rarely,1254,Sales,10,3,Life Sciences,1,1869,...,80,3,14,2,3,8,7,0,7,senior
1395,31,Yes,Travel_Frequently,754,Sales,26,4,Marketing,1,1967,...,80,0,10,4,3,10,7,0,8,senior
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,80,2,12,3,3,6,3,0,1,mid-level

In [27]:
# Employees with high job satisfaction who left
df[(df["JobSatisfaction"] == 4) & (df["Attrition"] == "Yes")]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,seniority_level
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,80,0,8,0,1,6,4,0,5,mid-level
33,39,Yes,Travel_Rarely,895,Sales,5,3,Technical Degree,1,42,...,80,1,19,6,4,1,0,0,0,junior
34,24,Yes,Travel_Rarely,813,Research & Development,1,3,Medical,1,45,...,80,1,6,2,2,2,0,2,0,junior
89,46,Yes,Travel_Rarely,669,Sales,9,2,Medical,1,118,...,80,0,9,3,3,9,8,4,7,senior
102,20,Yes,Travel_Frequently,871,Research & Development,6,3,Life Sciences,1,137,...,80,0,1,5,3,1,0,1,0,junior
126,58,Yes,Travel_Rarely,147,Research & Development,23,4,Medical,1,165,...,80,1,40,3,2,40,10,15,6,senior
136,51,Yes,Travel_Frequently,1150,Research & Development,8,4,Life Sciences,1,179,...,80,0,18,2,3,4,2,0,3,mid-level
177,19,Yes,Travel_Rarely,303,Research & Development,2,3,Life Sciences,1,243,...,80,0,1,3,2,1,0,1,0,junior
205,29,Yes,Travel_Rarely,121,Sales,27,3,Marketing,1,283,...,80,3,10,3,2,10,4,1,9,senior
210,32,Yes,Travel_Rarely,1045,Sales,4,4,Medical,1,291,...,80,0,14,2,2,14,8,9,8,senior
229,29,Yes,Travel_Rarely,896,Research & Development,18,1,Medical,1,315,...,80,0,4,3,2,4,3,0,1,mid-level
234,33,Yes,Travel_Rarely,813,Research & Development,14,3,Medical,1,325,...,80,1,8,2,1,5,4,0,4,mid-level
293,26,Yes,Travel_Rarely,950,Sales,4,4,Marketing,1,401,...,80,0,8,0,3,8,7,7,4,senior
323,28,Yes,Travel_Rarely,1157,Research & Development,2,4,Medical,1,440,...,80,0,5,4,2,3,2,2,2,mid-level
378,34,Yes,Non-Travel,1362,Sales,19,3,Marketing,1,502,...,80,0,9,3,2,5,2,0,4,mid-level
385,30,Yes,Travel_Frequently,464,Research & Development,4,3,Technical Degree,1,514,...,80,0,3,4,3,1,0,0,0,junior
422,19,Yes,Travel_Rarely,489,Human Resources,2,2,Technical Degree,1,566,...,80,0,1,3,4,1,0,0,0,junior
436,33,Yes,Travel_Rarely,587,Research & Development,10,1,Medical,1,584,...,80,3,8,2,3,4,3,1,3,mid-level
463,26,Yes,Travel_Rarely,471,Research & Development,24,3,Technical Degree,1,622,...,80,0,1,3,1,1,0,0,0,junior
562,33,Yes,Travel_Rarely,527,Research & Development,1,4,Other,1,780,...,80,0,10,2,2,10,9,7,8,senior
607,49,Yes,Travel_Rarely,1184,Sales,11,3,Marketing,1,840,...,80,2,9,3,4,9,8,7,7,senior
608,55,Yes,Travel_Rarely,436,Sales,2,1,Medical,1,842,...,80,0,12,3,2,9,7,7,3,senior
656,32,Yes,Travel_Rarely,374,Research & Development,25,4,Life Sciences,1,911,...,80,0,1,2,1,1,0,0,1,junior
660,58,Yes,Travel_Frequently,781,Research & Development,2,1,Life Sciences,1,918,...,80,1,3,3,2,1,0,0,0,junior
663,21,Yes,Travel_Rarely,1427,Research & Development,18,1,Other,1,923,...,80,0,1,3,2,1,0,0,0,junior
667,41,Yes,Travel_Rarely,1085,Research & Development,2,4,Life Sciences,1,927,...,80,1,10,1,2,7,7,1,0,senior
693,36,Yes,Travel_Rarely,530,Sales,3,1,Life Sciences,1,967,...,80,1,16,6,3,16,7,3,7,senior
749,52,Yes,Travel_Rarely,266,Sales,2,1,Marketing,1,1038,...,80,1,33,3,3,32,14,6,9,senior
776,20,Yes,Travel_Frequently,769,Sales,9,3,Marketing,1,1077,...,80,0,2,3,3,2,2,0,2,junior
796,25,Yes,Travel_Rarely,1219,Research & Development,4,1,Technical Degree,1,1106,...,80,1,7,3,4,7,7,5,6,senior
813,39,Yes,Travel_Frequently,203,Research & Development,2,3,Life Sciences,1,1127,...,80,3,21,4,3,18,7,11,5,senior
842,28,Yes,Travel_Rarely,1485,Research & Development,12,1,Life Sciences,1,1175,...,80,0,1,4,2,1,1,0,0,junior
860,22,Yes,Travel_Frequently,1256,Research & Development,3,4,Life Sciences,1,1203,...,80,1,1,5,3,0,0,0,0,junior
911,25,Yes,Travel_Frequently,599,Sales,24,1,Life Sciences,1,1273,...,80,0,1,4,3,1,0,1,0,junior
928,44,Yes,Travel_Rarely,621,Research & Development,15,3,Medical,1,1295,...,80,1,10,2,3,10,7,0,5,senior
980,31,Yes,Travel_Frequently,703,Sales,2,3,Life Sciences,1,1379,...,80,0,3,3,4,1,0,0,0,junior
1007,29,Yes,Travel_Frequently,337,Research & Development,14,1,Other,1,1421,...,80,0,9,1,3,8,7,7,7,senior
1031,46,Yes,Travel_Rarely,377,Sales,9,3,Marketing,1,1457,...,80,1,28,1,4,7,7,4,3,senior
1036,31,Yes,Travel_Frequently,523,Research & Development,2,3,Life Sciences,1,1464,...,80,1,7,2,1,2,2,2,2,junior
1111,53,Yes,Travel_Rarely,607,Research & Development,2,5,Technical Degree,1,1572,...,80,1,34,4,3,33,7,1,9,senior
1153,18,Yes,Travel_Frequently,544,Sales,3,2,Medical,1,1624,...,80,0,0,2,4,0,0,0,0,junior
1167,35,Yes,Travel_Rarely,763,Sales,15,2,Medical,1,1645,...,80,2,7,2,2,2,2,2,2,junior
1186,35,Yes,Travel_Frequently,880,Sales,12,4,Other,1,1667,...,80,0,13,2,4,11,9,6,7,senior
1213,23,Yes,Travel_Rarely,427,Sales,7,3,Life Sciences,1,1702,...,80,1,3,2,3,3,2,0,2,mid-level
1246,30,Yes,Travel_Frequently,600,Human Resources,8,3,Human Resources,1,1747,...,80,1,6,0,2,4,2,1,2,mid-level
1281,35,Yes,Travel_Rarely,303,Sales,27,3,Life Sciences,1,1797,...,80,0,10,2,3,10,7,7,7,senior
1332,29,Yes,Travel_Frequently,459,Research & Development,24,2,Life Sciences,1,1868,...,80,0,1,3,2,1,0,1,0,junior
1338,30,Yes,Travel_Rarely,945,Sales,9,3,Medical,1,1876,...,80,0,1,3,2,1,0,0,0,junior
1354,56,Yes,Travel_Rarely,1162,Research & Development,24,2,Life Sciences,1,1907,...,80,0,5,3,3,4,2,1,0,mid-level
1390,28,Yes,Travel_Rarely,1404,Research & Development,17,3,Technical Degree,1,1960,...,80,1,6,2,2,4,1,0,3,mid-level
1395,31,Yes,Travel_Frequently,754,Sales,26,4,Marketing,1,1967,...,80,0,10,4,3,10,7,0,8,senior
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,80,3,4,3,4,2,2,2,2,junior

<br>

## Step 9. Group by multiple columns

Group by JobRole and seniority_level and calculate the average MonthlyIncome.

In [ ]:
df.groupby(["JobRole", "seniority_level"])["MonthlyIncome"].mean()

JobRole                    seniority_level
Healthcare Representative  junior              6827.444444
                           mid-level           6722.404762
                           senior              8183.563380
Human Resources            junior              3077.538462
                           mid-level           4052.695652
                           senior              5439.937500
Laboratory Technician      junior              2808.818182
                           mid-level           3088.031915
                           senior              3908.779221
Manager                    junior             16910.071429
                           mid-level          16620.187500
                           senior             17359.263889
Manufacturing Director     junior              6719.222222
                           mid-level           6593.884615
                           senior              7919.560000
Research Director          junior             16477.500000
                           mid-level          16697.263158
                           senior             15699.235294
Research Scientist         junior              2784.305882
                           mid-level           3142.186047
                           senior              3898.256410
Sales Executive            junior              6888.062500
                           mid-level           6117.045045
                           senior              7471.233533
Sales Representative       junior              2307.500000
                           mid-level           2999.000000
                           senior              3202.000000
Name: MonthlyIncome, dtype: float64

<br>

## Step 10. Create a new column for income per year at the company
Create a new column income_per_year by dividing the employee's MonthlyIncome by the number of years at the company. Handle cases where YearsAtCompany is 0 (to avoid division by zero).

In [34]:
df["income_per_year"] = df["MonthlyIncome"] / df["YearsAtCompany"].replace(0, np.nan, inplace=True)
df

C:\Users\MIka\AppData\Local\Temp\ipykernel_33124\717975245.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["income_per_year"] = df["MonthlyIncome"] / df["YearsAtCompany"].replace(0, np.nan, inplace=True)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,seniority_level,income_per_year
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,0,8,0,1,6,4,0,5,mid-level,998.833333
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,1,10,3,3,10,7,1,7,senior,513.000000
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,0,7,3,3,0,0,0,0,junior,NaN
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,0,8,3,3,8,7,3,0,senior,363.625000
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,1,6,3,3,2,2,2,2,junior,1734.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,1,17,3,3,5,2,0,3,mid-level,514.200000
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,9,5,3,7,7,1,7,senior,1427.285714
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,1,6,0,3,6,2,0,3,mid-level,1023.666667
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,0,17,3,2,9,6,0,8,senior,598.888889
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,0,6,3,4,4,3,1,2,mid-level,1101.000000

<br>

## Step 11. Pivot tables for attrition analysis

1. Create a pivot table to analyze attrition by Department and JobSatisfaction.
1. reate another pivot table to analyze attrition by seniority_level and WorkLifeBalance.

In [35]:
# Attrition by Department and JobSatisfaction
pd.pivot_table(df, 
               values="Attrition", 
               index="Department", 
               columns="JobSatisfaction", 
               aggfunc=lambda x: (x == "Yes").mean() * 100)

JobSatisfaction                 1          2          3          4
Department
Human Resources         45.454545  10.000000  20.000000  11.764706
Research & Development  19.791667  13.793103  14.333333   9.491525
Sales                   26.744186  23.255814  21.259843  14.965986

In [36]:
# Attrition by Seniority level and WorkLifeBalance
pd.pivot_table(df, 
               values="Attrition", 
               index="seniority_level", 
               columns="WorkLifeBalance", 
               aggfunc=lambda x: (x == "Yes").mean() * 100)

WorkLifeBalance          1          2          3          4
seniority_level
junior           47.619048  36.986301  24.423963  38.709677
mid-level        25.000000   9.677419  14.429530  10.714286
senior           25.925926  12.925170   8.201058  13.636364

<br>

<hr>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=520e70a9-b7fd-4903-be7f-b6533a9e0dcb' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>