<br>

---

<br>

# Pandas Basic Exercise #1

Total Question: 15 Task
Topic: Series, DataFrame, Pandas Indexing

> <br>
> Notebook mohon untuk TIDAK di RUN-ALL, buat blok baru untuk menjawab soal<br>
> <br>

## Step 1.

Import the required libraries

In [2]:
import pandas as pd

<br>

**Figure 1.**

| Name  | Age | Gender | Job              | Location          |
|-------|-----|--------|------------------|-------------------|
| Andi  | 24  | Male   | Data Analyst     | Jakarta           |
| Budi  | 25  | Male   | Data Analyst     | Tangerang Selatan |
| Caca  | 30  | Female | Data Scientist   | Jakarta           |
| Dedi  | 32  | Female | Data Scientist   | Bandung           |
| Erika | 28  | Female | Data Analyst     | Jakarta           |
| Fahri | 24  | Male   | Data Engineer    | Surabaya          |
| Gina  | 29  | Female | ML Engineer      | Bandung           |
| Hani  | 31  | Female | ML Researcher    | Yogyakarta        |
| Indro | 30  | Male   | BI Analyst       | Jakarta           |
| Jarot | 29  | Male   | Data Analyst     | Tangerang Selatan |

## Step 2.

Create a dictionary with 5 keys and each key has a value in the form of a list with 10 items. The contents of the dictionary follow the output of **Figure 1.**.

In [51]:
data = {
    "Name":     ["Andi", "Budi", "Caca", "Dedi", "Erika", "Fahri", "Gina", "Hani", "Indro", "Jarot"],
    "Age":      [24, 25, 30, 32, 28, 24, 29, 31, 30, 29],
    "Gender":   ["Male", "Male", "Female", "Female", "Female", "Male", "Female", "Female", "Male", "Male"],
    "Location": ["Jakarta", "Tangerang Selatan", "Jakarta", "Bandung", "Jakarta", "Surabaya", "Bandung", "Yogyakarta", "Jakarta", "Tangerang Selatan"]
}
df = pd.DataFrame(data)

<br>

## Step 3.

Create a DataFrame using the data dictionary in **step 2** and store it in the variable df.

In [13]:
print(df)

    Name  Age  Gender           Location
0   Andi   24    Ma;e            Jakarta
1   Budi   25    Male  Tangerang Selatan
2   Caca   30  Female            Jakarta
3   Dedi   32  Female            Bandung
4  Erika   28  Female            Jakarta
5  Fahri   24    Male           Surabaya
6   Gina   29  Female            Bandung
7   Hani   31  Female         Yogyakarta
8  Indro   30    Male            Jakarta
9  Jarot   29    Male  Tangerang Selatan

<br>

## Step 4.
Change the order of the columns to be as follows: Name, Gender, Age, Location, Job.

In [57]:
df["Job"] = ["Data Analyst", "Data Engineer", "Data Scientist", "Data Scientist", "Data Analyst", "Data Engineer", "ML Engineer", "ML Researcher", "BI Analyst", "Data Analyst"]
df = df[["Name", "Gender", "Age", "Location", "Job"]]
print(df)

    Name  Gender  Age           Location             Job
0   Andi    Male   24            Jakarta    Data Analyst
1   Budi    Male   25  Tangerang Selatan   Data Engineer
2   Caca  Female   30            Jakarta  Data Scientist
3   Dedi  Female   32            Bandung  Data Scientist
4  Erika  Female   28            Jakarta    Data Analyst
5  Fahri    Male   24           Surabaya   Data Engineer
6   Gina  Female   29            Bandung     ML Engineer
7   Hani  Female   31         Yogyakarta   ML Researcher
8  Indro    Male   30            Jakarta      BI Analyst
9  Jarot    Male   29  Tangerang Selatan    Data Analyst

## Step 5. 
Add 1 new column named 'Hobby' and fill in the data as shown in the following output.

In [58]:
df["Hobby"] = ["Gaming", "Futsal", "Reading", "Gaming", "Cooking", "Traveling", "Basketball", "Traveling", "Futsal", "Gaming"]
df = df[["Name", "Gender", "Age", "Location", "Job", "Hobby"]]
print(df)

    Name  Gender  Age           Location             Job       Hobby
0   Andi    Male   24            Jakarta    Data Analyst      Gaming
1   Budi    Male   25  Tangerang Selatan   Data Engineer      Futsal
2   Caca  Female   30            Jakarta  Data Scientist     Reading
3   Dedi  Female   32            Bandung  Data Scientist      Gaming
4  Erika  Female   28            Jakarta    Data Analyst     Cooking
5  Fahri    Male   24           Surabaya   Data Engineer   Traveling
6   Gina  Female   29            Bandung     ML Engineer  Basketball
7   Hani  Female   31         Yogyakarta   ML Researcher   Traveling
8  Indro    Male   30            Jakarta      BI Analyst      Futsal
9  Jarot    Male   29  Tangerang Selatan    Data Analyst      Gaming

<br>

## Step 6.
Use **.iloc** to retrieve data for Dedi, Fahri, Hani

In [79]:
ilocfilter = df.iloc[[3, 5, 7]]
print(ilocfilter)

#Alternative Solution
cond = df["Name"].isin(values = ["Dedi", "Fahri", "Hani"])
df.loc[cond]

    Name  Gender  Age    Location             Job      Hobby
3   Dedi  Female   32     Bandung  Data Scientist     Gaming
5  Fahri    Male   24    Surabaya   Data Engineer  Traveling
7   Hani  Female   31  Yogyakarta   ML Researcher  Traveling

    Name  Gender  Age    Location             Job      Hobby
3   Dedi  Female   32     Bandung  Data Scientist     Gaming
5  Fahri    Male   24    Surabaya   Data Engineer  Traveling
7   Hani  Female   31  Yogyakarta   ML Researcher  Traveling

<br>

## Step 7.
Use **.loc** to display the name, location and job of **Caca** and **Indro**

In [60]:
step7 = (df.loc[[2, 8], ["Name", "Location", "Job"]])
print(step7)

    Name Location             Job
2   Caca  Jakarta  Data Scientist
8  Indro  Jakarta      BI Analyst

<br>

## Step 8.

Use **.loc** to display all data from **Hani**, **Indro**, **Jarot**

In [61]:
step8 = df.loc[7:9]
print (step8)

    Name  Gender  Age           Location            Job      Hobby
7   Hani  Female   31         Yogyakarta  ML Researcher  Traveling
8  Indro    Male   30            Jakarta     BI Analyst     Futsal
9  Jarot    Male   29  Tangerang Selatan   Data Analyst     Gaming

<br>

## Step 9.
Who is over 30 years old?

In [85]:
step9 = df['Age'] > 30
display(df.loc[step9,:])

#Alternative solution
display(df.loc[(df["Age"]>30), "Name"])

   Name  Gender  Age    Location             Job      Hobby
3  Dedi  Female   32     Bandung  Data Scientist     Gaming
7  Hani  Female   31  Yogyakarta   ML Researcher  Traveling

3    Dedi
7    Hani
Name: Name, dtype: str

<br>

## Step 10.
Who is **under 30** years old and whose hobby is **gaming**?

In [63]:
step10age = df ["Age"] < 30  
step10hobby = df ["Hobby"] == "Gaming"
df.loc[step10age | step10hobby]

    Name  Gender  Age           Location             Job       Hobby
0   Andi    Male   24            Jakarta    Data Analyst      Gaming
1   Budi    Male   25  Tangerang Selatan   Data Engineer      Futsal
3   Dedi  Female   32            Bandung  Data Scientist      Gaming
4  Erika  Female   28            Jakarta    Data Analyst     Cooking
5  Fahri    Male   24           Surabaya   Data Engineer   Traveling
6   Gina  Female   29            Bandung     ML Engineer  Basketball
9  Jarot    Male   29  Tangerang Selatan    Data Analyst      Gaming

<br>

## Step 11.
Show the name of the person whose job is Data Analyst! Show only the name column in Series form!

In [70]:
step11 = df[df["Job"] == "Data Analyst"]["Name"]
print(step11)

0     Andi
4    Erika
9    Jarot
Name: Name, dtype: str

<br>

## Step 12.
What are the jobs of people who live in Jakarta? Show their names and jobs!

In [71]:
step12 = df[df["Location"] == "Jakarta"][["Name", "Job"]]
print(step12)

    Name             Job
0   Andi    Data Analyst
2   Caca  Data Scientist
4  Erika    Data Analyst
8  Indro      BI Analyst

<br>

## Step 13.
What are the hobbies of the women in the data? Show only the Name, Hobby, Age columns in order!

In [72]:
step13 = df[df["Gender"] == "Female"][["Name", "Hobby", "Age"]]
print(step13)

    Name       Hobby  Age
2   Caca     Reading   30
3   Dedi      Gaming   32
4  Erika     Cooking   28
6   Gina  Basketball   29
7   Hani   Traveling   31

<br>

## Step 14.
Who is older than Erika? Show only the name column in DataFrame!

In [73]:
step14 = df[df["Age"] > 28]["Name"]
print(step14)

2     Caca
3     Dedi
6     Gina
7     Hani
8    Indro
9    Jarot
Name: Name, dtype: str

<br>

## Step 15.
Based on the data, are there any women whose hobby is traveling?

In [77]:
result = df[(df["Gender"] == "Female") & (df["Hobby"] == "Traveling")].any().any()
print(result)

True

## Step 16.
Export dataframe into csv file with name `ep1_data.csv` (without index) in the current folder.

In [78]:
df.to_csv('day5exercise.csv')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=520e70a9-b7fd-4903-be7f-b6533a9e0dcb' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>